#pragma once

#define STLR_MOUSE_BUTTON_1         0
#define STLR_MOUSE_BUTTON_2         1
#define STLR_MOUSE_BUTTON_3         2
#define STLR_MOUSE_BUTTON_4         3
#define STLR_MOUSE_BUTTON_5         4
#define STLR_MOUSE_BUTTON_6         5
#define STLR_MOUSE_BUTTON_7         6
#define STLR_MOUSE_BUTTON_8         7
#define STLR_MOUSE_BUTTON_LAST      STLR_MOUSE_BUTTON_8
#define STLR_MOUSE_BUTTON_LEFT      STLR_MOUSE_BUTTON_1
#define STLR_MOUSE_BUTTON_RIGHT     STLR_MOUSE_BUTTON_2
#define STLR_MOUSE_BUTTON_MIDDLE    STLR_MOUSE_BUTTON_3